### ISSUE TITLE
reading configuration from file fails upon startup

### ISSUE THREAD

**Issue by donaldsharp** [udhos/qpimd#3]
I am getting this error message:

pim_if_add_vif: ifindex=0 < 1 on interface swp1

It is happening because in pim_main.c:main() we are initializing zebra with pim_zebra_init() after we read in the configuration with vty_read_config().  This patch fixes this issue:
diff --git a/pimd/pim_main.c b/pimd/pim_main.c
index c646356..b57f881 100644
--- a/pimd/pim_main.c
+++ b/pimd/pim_main.c
@@ -216,6 +216,11 @@ int main(int argc, char*\* argv, char*\* envp) {
   zlog_default->maxlvl[ZLOG_DEST_STDOUT] = ZLOG_DISABLED;
 #endif
-  /*
-    Initialize zclient "update" and "lookup" sockets
-   */
-  pim_zebra_init(zebra_sock_path);
  +
  zlog_notice("Loading configuration - begin");
  
  /\* Get configuration file. _/
  @@ -278,12 +283,6 @@ int main(int argc, char_\* argv, char*\* envp) {
  zlog_notice("!HAVE_CLOCK_MONOTONIC");
  # endif
## 
-  /*
-    Initialize zclient "update" and "lookup" sockets
-   */
## \-  pim_zebra_init(zebra_sock_path);

   while (thread_fetch(master, &thread))
     thread_call(&thread);

donald

**Comment by udhos** [comment]
Donald, thanks for the contribution.

I am looking at it.

Not sure if you are aware of github pull requests (https://help.github.com/articles/using-pull-requests/), but they are helpful (and fun) in simplifying the workflow of applying patches.

No need to resend the patch as pull request, but please consider that tool if you plan to contribute often. ;-)

Cheers.

**Comment by donaldsharp** [comment]
I'll start using the github pull requests, thanks for the information.  I'm
still new to using git.  My old company used an entirely different system
for SCM.

Now I'm not sure I've fixed the issue.  Sometimes when I stop/start I see
the issue, sometimes I don't now.  I was just attempting to make the zebra
initialization the same as what I saw in bgp.  I am working in a
significantly modified version of quagga than what pimd was written
against, so it might be some other issue that I am running into now.  But
it was the only thing that immediately made sense to me as why the ifindex
for the interface would be 0( if zebra was not initialized properly yet ).
I do know that if I wait until startup has fully finished I never see the
error, thus implying some sort of race condition I am seeing.

donald

**Comment by udhos** [comment]
Applied as https://github.com/udhos/qpimd/commit/da5a7f9c5ea1fd5f242b2459e32c80661b337b36

**Comment by udhos** [comment]
I still see the warnings if the zebra daemon can't be contacted at pimd booting time. But your patch did improve things a little bit for me in the usual case.

**Comment by donaldsharp** [comment]
I'll ask around here some about what is going on.  Someone might have a
clue.

donald

**Comment by udhos** [comment]
I think there are two cases when pimd can find out the interface's ifindex:

1) Zebra lib reports a new interface (only if interface is created after pimd boot):
2015/01/19 18:29:53 PIM: INTERFACE UP: tunl0 ifindex=5

2) Zebra lib reports a new address for interface (most common case):
2015/01/19 18:35:11 PIM: pim_if_addr_add: eth0 ifindex=2 connected IP address 10.0.2.15/24 primary
2015/01/19 18:35:11 PIM: on_primary_address_change: pim_if_addr_add: primary address changed from 0.0.0.0 to 10.0.2.15 on interface eth0
2015/01/19 18:35:11 PIM: pim_if_dr_election: DR was 0.0.0.0 now is 10.0.2.15 on interface eth0
2015/01/19 18:35:11 PIM: PIM INTERFACE UP: on interface eth0 ifindex=2

However those events can only take place _after_ loading the config, because they are dispatched from the thread management loop at the end of pim_main.c:

  while (thread_fetch(master, &thread))
    thread_call(&thread);

**Comment by udhos** [comment]
Donald, I think I will revert this patch, because it does not seem to achieve the intended effect. Let me know if you disagree. Thanks

**Comment by donaldsharp** [comment]
Part of the motivation for this patch from my opinion was to make pimd
initialize like the other daemons do.  All the other ones do the zebra
configuration prior to the reading in of the configuration file.  This
allows us to ensure that any subtle zebra changes made in the future work
as expected like the other protocols.  In the end I'm not going to get too
hung up about the issue.

donald

**Comment by udhos** [comment]
We can leave the change in place, no problem about that, because it does no harm. Poor thing is its description is misleading.

**Comment by donaldsharp** [comment]
Question:

The 'ip pim ssm' command calls pim_if_addr_add_all(), which in turns call
pim_if_addr_add which has this comment:

  if (PIM_MROUTE_IS_ENABLED) {
    /*
      PIM or IGMP is enabled on interface, and there is at least one
      address assigned, then try to create a vif_index.
    */
    if (pim_ifp->mroute_vif_index < 0) {
      pim_if_add_vif(ifp);
    }

Should we be calling this code at this point in startup?  I've verified
that we don't actually know the address, I added this line to
pim_if_addr_add

  zlog_notice("%s: ifp: %s %d %d", **PRETTY_FUNCTION**, ifp->name,
ifp->ifindex, ifc->address->u.prefix4);

am getting this output:

2015/01/20 21:00:18.785365 PIM: pim_if_new: ifp: swp1 0
2015/01/20 21:00:18.786147 PIM: pim_if_add_vif: ifindex=0 < 1 on interface
swp1

seems like we should be checking to see if there is actually a valid
address on the interface before we call pim_if_add_vif()?

donald

**Comment by udhos** [comment]
What is the objective? Only to remove the message "pim_if_add_vif: ifindex=0 < 1 on interface swp1" from logs? When pimd is reading the configuration at boot time, it didn't  communicate with zebrad yet -- in order to find which interfaces actually exist. We can try to prevent that message from being logged but fact is at boot time pimd won't be able to pinpoint actual interfaces.

**Comment by udhos** [comment]
Look at this comment from pim_cmd.c:

DEFUN (pim_interface,
       pim_interface_cmd,
       "interface IFNAME",
       "Select an interface to configure\n"
       "Interface's name\n")
{
  struct interface *ifp;
  const char *ifname = argv[0];
  size_t sl;

  sl = strlen(ifname);
  if (sl > INTERFACE_NAMSIZ) {
    vty_out(vty, "%% Interface name %s is invalid: length exceeds "
            "%d characters%s",
            ifname, INTERFACE_NAMSIZ, VTY_NEWLINE);
    return CMD_WARNING;
  }

  ifp = if_lookup_by_name_len(ifname, sl);
  if (!ifp) {
    vty_out(vty, "%% Interface %s does not exist%s", ifname, VTY_NEWLINE);

```
/* Returning here would prevent pimd from booting when there are
   interface commands in pimd.conf, since all interfaces are
   unknown at pimd boot time (the zebra daemon has not been
   contacted for interface discovery). */

ifp = if_get_by_name_len(ifname, sl);
if (!ifp) {
  vty_out(vty, "%% Could not create interface %s%s", ifname, VTY_NEWLINE);
  return CMD_WARNING;
}
```

  }

  vty->index = ifp;
  vty->node = INTERFACE_NODE;

  return CMD_SUCCESS;
}

**Comment by donaldsharp** [comment]
So I'm back looking at pim-ssm again. I'm going to be making changes how
would you like me to proceed?  Send questions/work here or to the quagga
dev alias?

Donald

**Comment by udhos** [comment]
Regarding discussion, I am fine either way.
We just need to be aware the official Quagga repo is more up-to-date than this one.
Then any discussion should reflect latest code hosted there.

**Comment by donaldsharp** [comment]
That's fine with me.  I've already started one discussion about an cli
issue I found

thanks!

donald
